app_code: rolllog
app_name: 日志管理
author: 贵州年华
category: 实用工具
introduction:一些三方软件日志持续增大，没有相应的管理。仅仅通过定期删除的方式，无法保留足够分析问题的日志量。本应用通过对这些重要日志做定期检查，当日志超过一定大小后，做日志文件序号循环处理。
version: 1.0.0
language: python, shell
is_use_celery: False
desktop:
    width: 1200
    height: 720
    is_max: False
date: 2018-06-27 12:00:00
